### ISSUE TITLE
Result for my arm board does not contain certain functions

### ISSUE THREAD

**Issue by sanaf1064** [ssvb/tinymembench#6]
even after compiling the way stated in the ReadMe, i am not getting values for 
MOVSB copy                                          
 MOVSD copy                                          
 SSE2 copy                                         
 SSE2 nontemporal copy                               
 SSE2 copy prefetched (32 bytes step)                
 SSE2 copy prefetched (64 bytes step)                 
 SSE2 nontemporal copy prefetched (32 bytes step)    
 SSE2 nontemporal copy prefetched (64 bytes step)   
 SSE2 2-pass copy                                    
 SSE2 2-pass copy prefetched (32 bytes step)         
 SSE2 2-pass copy prefetched (64 bytes step)        
 SSE2 2-pass nontemporal copy                        
 SSE2 fill                                           
 SSE2 nontemporal fill          
whereas i got for my x86
 nor the functions stated for arm in results of raspberry 
VFP copy                                             :    162.3 MB/s
 VFP 2-pass copy                                      :    141.2 MB/s
 ARM fill (STRD)                                      :    744.4 MB/s
 ARM fill (STM with 8 registers)                      :   1090.7 MB/s
 ARM fill (STM with 4 registers)                      :   1458.4 MB/s
 ARM copy prefetched (incr pld)                       :    387.6 MB/s
 ARM copy prefetched (wrap pld)                       :    207.3 MB/s
 ARM 2-pass copy prefetched (incr pld)                :    283.3 MB/s
 ARM 2-pass copy prefetched (wrap pld)                :    229.0 MB/s

can u plz tell me why

**Comment by ssvb** [comment]
What are you getting exactly?

**Comment by sanaf1064** [comment]
hi Siarhei Siamashka,

i am actually trying to compare my arm64 board and x86 pc
with the latest releasei.e 0.4 i got following output as attached .
*Both execution do not have same key value pair.*
so i can not compare all the values.
And comparing with common keys for both execution will be under utilization
of timymembench.
Can you tell me from where to read for each value what is the operation
performed and why some values are not there for arm64








On Tue, Mar 15, 2016 at 3:23 AM, Siarhei Siamashka <notifications@github.com
> wrote:

> What are you getting exactly?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ssvb/tinymembench/issues/6#issuecomment-196537323>.
>

%%%         tinymembench test start       %%% 
<<<BEGIN TEST>>>
[test: tinymembench]
log: ./bin/tinymembench
tinymembench v (simple benchmark for memory throughput and latency)

==========================================================================
== Memory bandwidth tests                                               ==
==                                                                      ==
== Note 1: 1MB = 1000000 bytes                                          ==
== Note 2: Results for 'copy' tests show how many bytes can be          ==
==         copied per second (adding together read and writen           ==
==         bytes would have provided twice higher numbers)              ==
== Note 3: 2-pass copy means that we are using a small temporary buffer ==
==         to first fetch data into it, and only then write it to the   ==
==         destination (source -> L1 cache, L1 cache -> destination)    ==
== Note 4: If sample standard deviation exceeds %, it is shown in    ==
==         brackets                                                     ==
==========================================================================

 C copy backwards                                     :    MB/s
 C copy backwards (32 byte blocks)                    :    MB/s
 C copy backwards (64 byte blocks)                    :    MB/s
 C copy                                               :    MB/s
 C copy prefetched (32 bytes step)                    :    MB/s
 C copy prefetched (64 bytes step)                    :    MB/s
 C 2-pass copy                                        :    MB/s
 C 2-pass copy prefetched (32 bytes step)             :    MB/s
 C 2-pass copy prefetched (64 bytes step)             :    MB/s
 C fill                                               :    MB/s (%)
 C fill (shuffle within 16 byte blocks)               :    MB/s
 C fill (shuffle within 32 byte blocks)               :    MB/s (%)
 C fill (shuffle within 64 byte blocks)               :    MB/s
 ---
 standard memcpy                                      :    MB/s
 standard memset                                      :    MB/s (%)
 ---
 NEON LDP/STP copy                                    :    MB/s
 NEON LD1/ST1 copy                                    :    MB/s
 NEON STP fill                                        :    MB/s (%)
 NEON STNP fill                                       :    MB/s (%)
 ARM LDP/STP copy                                     :    MB/s
 ARM STP fill                                         :    MB/s
 ARM STNP fill                                        :    MB/s

==========================================================================
== Memory latency test                                                  ==
==                                                                      ==
== Average time is measured for random memory accesses in the buffers   ==
== of different sizes. The larger is the buffer, the more significant   ==
== are relative contributions of TLB, L1/L2 cache misses and SDRAM      ==
== accesses. For extremely large buffer sizes we are expecting to see   ==
== page table walk with several requests to SDRAM for almost every      ==
== memory access (though 64MiB is not nearly large enough to experience ==
== this effect to its fullest).                                         ==
==                                                                      ==
== Note 1: All the numbers are representing extra time, which needs to  ==
==         be added to L1 cache latency. The cycle timings for L1 cache ==
==         latency can be usually found in the processor documentation. ==
== Note 2: Dual random read means that we are simultaneously performing ==
==         two independent memory accesses at a time. In the case if    ==
==         the memory subsystem can't handle multiple outstanding       ==
==         requests, dual random read has the same timings as two       ==
==         single reads performed one after another.                    ==
==========================================================================

block size : single random read / dual random read, [MADV_NOHUGEPAGE]
      1024 :     ns          /      ns 
      2048 :     ns          /      ns 
      4096 :     ns          /      ns 
      8192 :     ns          /      ns 
     16384 :     ns          /      ns 
     32768 :     ns          /      ns 
     65536 :     ns          /      ns 
    131072 :     ns          /      ns 
    262144 :     ns          /     ns 
    524288 :    ns          /     ns 
   1048576 :    ns          /     ns 
   2097152 :    ns          /     ns 
   4194304 :    ns          /     ns 
   8388608 :    ns          /     ns 
  16777216 :    ns          /    ns 
  33554432 :   ns          /    ns 
  67108864 :   ns          /    ns 

block size : single random read / dual random read, [MADV_HUGEPAGE]
      1024 :     ns          /      ns 
      2048 :     ns          /      ns 
      4096 :     ns          /      ns 
      8192 :     ns          /      ns 
     16384 :     ns          /      ns 
     32768 :     ns          /      ns 
     65536 :     ns          /      ns 
    131072 :     ns          /      ns 
    262144 :     ns          /      ns 
    524288 :     ns          /      ns 
   1048576 :    ns          /     ns 
   2097152 :    ns          /     ns 
   4194304 :    ns          /     ns 
   8388608 :    ns          /     ns 
  16777216 :    ns          /     ns 
  33554432 :   ns          /    ns 
  67108864 :   ns          /    ns 
[status]: PASS
Time in Seconds: s
<<<END>>>
%%%%%% test_end %%%%%%

%%%         tinymembench test start       %%% 
<<<BEGIN TEST>>>
[test: tinymembench]
log: ./bin/tinymembench
tinymembench v (simple benchmark for memory throughput and latency)

==========================================================================
== Memory bandwidth tests                                               ==
==                                                                      ==
== Note 1: 1MB = 1000000 bytes                                          ==
== Note 2: Results for 'copy' tests show how many bytes can be          ==
==         copied per second (adding together read and writen           ==
==         bytes would have provided twice higher numbers)              ==
== Note 3: 2-pass copy means that we are using a small temporary buffer ==
==         to first fetch data into it, and only then write it to the   ==
==         destination (source -> L1 cache, L1 cache -> destination)    ==
== Note 4: If sample standard deviation exceeds %, it is shown in    ==
==         brackets                                                     ==
==========================================================================

 C copy backwards                                     :    MB/s (%)
 C copy backwards (32 byte blocks)                    :    MB/s
 C copy backwards (64 byte blocks)                    :    MB/s
 C copy                                               :    MB/s
 C copy prefetched (32 bytes step)                    :    MB/s
 C copy prefetched (64 bytes step)                    :    MB/s
 C 2-pass copy                                        :    MB/s
 C 2-pass copy prefetched (32 bytes step)             :    MB/s
 C 2-pass copy prefetched (64 bytes step)             :    MB/s
 C fill                                               :    MB/s
 C fill (shuffle within 16 byte blocks)               :    MB/s
 C fill (shuffle within 32 byte blocks)               :    MB/s
 C fill (shuffle within 64 byte blocks)               :    MB/s
 ---
 standard memcpy                                      :    MB/s (%)
 standard memset                                      :    MB/s (%)
 ---
 MOVSB copy                                           :    MB/s
 MOVSD copy                                           :    MB/s (%)
 SSE2 copy                                            :    MB/s
 SSE2 nontemporal copy                                :    MB/s (%)
 SSE2 copy prefetched (32 bytes step)                 :    MB/s
 SSE2 copy prefetched (64 bytes step)                 :    MB/s
 SSE2 nontemporal copy prefetched (32 bytes step)     :    MB/s
 SSE2 nontemporal copy prefetched (64 bytes step)     :    MB/s
 SSE2 2-pass copy                                     :    MB/s
 SSE2 2-pass copy prefetched (32 bytes step)          :    MB/s
 SSE2 2-pass copy prefetched (64 bytes step)          :    MB/s
 SSE2 2-pass nontemporal copy                         :    MB/s
 SSE2 fill                                            :    MB/s
 SSE2 nontemporal fill                                :   MB/s

==========================================================================
== Framebuffer read tests.                                              ==
==                                                                      ==
== Many ARM devices use a part of the system memory as the framebuffer, ==
== typically mapped as uncached but with write-combining enabled.       ==
== Writes to such framebuffers are quite fast, but reads are much       ==
== slower and very sensitive to the alignment and the selection of      ==
== CPU instructions which are used for accessing memory.                ==
==                                                                      ==
== Many x86 systems allocate the framebuffer in the GPU memory,         ==
== accessible for the CPU via a relatively slow PCI-E bus. Moreover,    ==
== PCI-E is asymmetric and handles reads a lot worse than writes.       ==
==                                                                      ==
== If uncached framebuffer reads are reasonably fast (at least 100 MB/s ==
== or preferably >300 MB/s), then using the shadow framebuffer layer    ==
== is not necessary in Xorg DDX drivers, resulting in a nice overall    ==
== performance improvement. For example, the xf86-video-fbturbo DDX     ==
== uses this trick.                                                     ==
==========================================================================

 MOVSD copy (from framebuffer)                        :       MB/s (%)
 MOVSD 2-pass copy (from framebuffer)                 :       MB/s (%)
 SSE2 copy (from framebuffer)                         :       MB/s (%)
 SSE2 2-pass copy (from framebuffer)                  :       MB/s (%)

==========================================================================
== Memory latency test                                                  ==
==                                                                      ==
== Average time is measured for random memory accesses in the buffers   ==
== of different sizes. The larger is the buffer, the more significant   ==
== are relative contributions of TLB, L1/L2 cache misses and SDRAM      ==
== accesses. For extremely large buffer sizes we are expecting to see   ==
== page table walk with several requests to SDRAM for almost every      ==
== memory access (though 64MiB is not nearly large enough to experience ==
== this effect to its fullest).                                         ==
==                                                                      ==
== Note 1: All the numbers are representing extra time, which needs to  ==
==         be added to L1 cache latency. The cycle timings for L1 cache ==
==         latency can be usually found in the processor documentation. ==
== Note 2: Dual random read means that we are simultaneously performing ==
==         two independent memory accesses at a time. In the case if    ==
==         the memory subsystem can't handle multiple outstanding       ==
==         requests, dual random read has the same timings as two       ==
==         single reads performed one after another.                    ==
==========================================================================

block size : single random read / dual random read, [MADV_NOHUGEPAGE]
      1024 :     ns          /      ns 
      2048 :     ns          /      ns 
      4096 :     ns          /      ns 
      8192 :     ns          /      ns 
     16384 :     ns          /      ns 
     32768 :     ns          /      ns 
     65536 :     ns          /      ns 
    131072 :     ns          /      ns 
    262144 :     ns          /      ns 
    524288 :    ns          /     ns 
   1048576 :    ns          /     ns 
   2097152 :    ns          /     ns 
   4194304 :    ns          /     ns 
   8388608 :    ns          /     ns 
  16777216 :    ns          /     ns 
  33554432 :    ns          /     ns 
  67108864 :    ns          /    ns 

block size : single random read / dual random read, [MADV_HUGEPAGE]
      1024 :     ns          /      ns 
      2048 :     ns          /      ns 
      4096 :     ns          /      ns 
      8192 :     ns          /      ns 
     16384 :     ns          /      ns 
     32768 :     ns          /      ns 
     65536 :     ns          /      ns 
    131072 :     ns          /      ns 
    262144 :     ns          /      ns 
    524288 :    ns          /     ns 
   1048576 :    ns          /     ns 
   2097152 :    ns          /     ns 
   4194304 :    ns          /     ns 
   8388608 :    ns          /     ns 
  16777216 :    ns          /     ns 
  33554432 :    ns          /     ns 
  67108864 :    ns          /     ns 
[status]: PASS
Time in Seconds: s
<<<END>>>
%%%%%% test_end %%%%%%

**Comment by sanaf1064** [comment]
yes /proc/cpuinfo is accessible in both

On Tue, Mar 15, 2016 at 3:23 AM, Siarhei Siamashka <notifications@github.com

**Comment by ssvb** [comment]
Closing because of the unclear question and missing feedback.
